### PR TITLE
Update target framework

### PR DESCRIPTION
**Pull request by jon-armen**
*Description of changes:*

Updating target frameworks for netcoreapp3.1 and dotnet6

Implementing ci pipeline

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by normj — CHANGES_REQUESTED** [review]
Can you pull out the CI build parts? I appreciate that GitHub actions would be better for external visibility but there is a whole internal review and appsec process we have to follow when we move to GitHub actions. As of right now the CI system for this repo is done using AWS Code services. We have started to move some of our newer repos to have some GitHub actions but like I said we have to go through a process to make that happen.

**Comment by jon-armen** [comment]
> Can you pull out the CI build parts? I appreciate that GitHub actions would be better for external visibility but there is a whole internal review and appsec process we have to follow when we move to GitHub actions. As of right now the CI system for this repo is done using AWS Code services. We have started to move some of our newer repos to have some GitHub actions but like I said we have to go through a process to make that happen.

Sure, I've updated the PR.  I also realized that removing the netstandard2.0 target would have technically been a breaking change.  I've left that in as to avoid any complications there.

**Review by saviour123 — APPROVED** [review]
The Ci segment has been removed. I think you should accept and merge this.

**Comment by normj** [comment]
The target framework was updated in a this PR https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet/pull/42. Sorry I should have done a better job coordinating between these 2 PRs and close/duplicated this sooner.

**Pull request closed without merging**
