### PR TITLE
Use structured logging

### PR DESCRIPTION
**Pull request by martincostello**
Update the log messages to use structured logging instead of string interpolation.

I noticed while looking at some logs that structured logging isn't used, so you don't get a template compared to, for example, ASP.NET Core's log output:

| **Source** | **MessageTemplate** | **RenderedMessage**
| :-- | :-- | :-- |
| `Microsoft.Hosting.Lifetime` | `Now listening on: {address}` | `Now listening on: "http://[::]:8080"` |
| `Amazon.AspNetCore.DataProtection.SSM.SSMXmlRepository` | `Using SSM Parameter Store to persist DataProtection keys with parameter name prefix MY_PREFIX` | `Using SSM Parameter Store to persist DataProtection keys with parameter name prefix MY_PREFIX` |

Open to suggestions of alternative names for the log properties in the templates, I just went with PascalCase names derived from what they were in terms of variables etc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by normj — APPROVED** [review]
Thanks, this is a good cleanup. 

I have been wondering for other projects if there is a default casing we should use. Pascal makes sense that is most commonly used in .NET, is that what you see in other projects is Pascal casing used as the default?

**Review by ashishdhingra — APPROVED** [review]
LGTM

Reference https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#create-logs

**Comment by normj** [comment]
@martincostello We were planning on doing a release next week adding a .NET 8 target. That release would include this PR.

**Comment by martincostello** [comment]
I'm AFK until Tuesday now. If you like I'll do a follow-up to add that for next week?

**Comment by normj** [comment]
> I'm AFK until Tuesday now. If you like I'll do a follow-up to add that for next week?

No worries, I'll take care of adding it.

**Comment by normj** [comment]
Version 3.2.0 is out with this PR. Thanks again.

**Pull request merged**
